<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount for-coupon" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="content" data-role="content" saria-labelledby="block-discount-heading" style="display:none;">
        <form id="discount-coupon-form"
              action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.apply",
                                               "cancelButton": "button.cancel"}}'>
            <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                    <div class="control">
                        <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?= $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?= $block->escapeHtml(__('Enter discount code')) ?>" <?php if (strlen($block->getCouponCode())): ?> disabled="disabled" <?php endif; ?> />
                    </div>				
                <div class="actions-toolbar">
                    <?php if (!strlen($block->getCouponCode())): ?>
                    <div class="primary">
                        <button class=" apply primary" type="button" value="<?= /* @escapeNotVerified */ __('Apply') ?>">
                            <span><?= /* @escapeNotVerified */ __('Apply') ?></span>
                        </button>
                    </div>
                    <?php else: ?>
                        <div class="primary">
                            <button  type="button" class=" cancel primary" value="<?= /* @escapeNotVerified */ __('Cancel') ?>"><span><?= /* @escapeNotVerified */ __('Cancel') ?></span></button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
	require(['jquery'],function($){
		$('.page-main .cart-summary .block.discount.for-coupon .coupon-title').click(function () {
			if($(this).hasClass('active')){
				$(this).removeClass('active');
				$('.page-main .cart-summary .block.discount .content').hide();
			}else{
				$(this).addClass('active');
				$('.page-main .cart-summary .block.discount .content').show();
			}
		});
	});
</script>