<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
echo $block->getSummaryCount();
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?= /* @escapeNotVerified */ __('Shopping Cart') ?></span>
	</h1>
	<a href="/"><?= /* @escapeNotVerified */ __('Continue Shopping') ?></a>
</div>
<form action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "/checkout/cart/updateItemQty"}
          }'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption"><?= /* @escapeNotVerified */ __('Shopping Cart Items') ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                    <th class="col price" scope="col"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                    <th class="col qty" scope="col"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
					<th class="col remove" scope="col">&nbsp;</th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
<script type="text/javascript">
	require(['jquery'],function($){
		$('.cart.table-wrapper .qty-block .qty_inc').click(function(){
			$(this).parent().parent().find("input.qty").val((+$(this).parent().parent().find("input.qty").val() + 1) || 0);
			$( "#form-validate" ).submit();
		});
		$('.cart.table-wrapper .qty-block .qty_dic').click(function(){
			if($(this).parent().parent().find("input.qty").val() > 1){
				$(this).parent().parent().find("input.qty").val((+$(this).parent().parent().find("input.qty").val() - 1) || 0);
				$( "#form-validate" ).submit();
			}
		});
	});
</script>
<script type="text/javascript">
	require(['jquery'],function($){
		$('.related .qty-block .qty_inc').click(function(){
			$(this).parent().find("input.qty").val((+$(this).parent().find("input.qty").val() + 1) || 0);
		});
		$('.related .qty-block .qty_dic').click(function(){
			if($(this).parent().find("input.qty").val() > 1){
				$(this).parent().find("input.qty").val((+$(this).parent().find("input.qty").val() - 1) || 0);
			}
		});
	});
</script>
<script>
    require(['jquery','slick-min'],function($){
        $(document).ready(function () {
            if ($(window).width() < 767) {
                $('.block.crosssell .product-items').slick({
                    dots: true,
                    infinite: true,
                    speed: 300,
                    slidesToShow: 1,
                    centerMode: true,
                    variableWidth: true,
                    arrows: false,
                    dots:false
                });
            }
        });
    });
</script>
