<script type="text/x-magento-init">
    {
        ".product-item-info .product-image-container img.product-image-photo": {
            "Magenest_ProductImageSwap/js/animation": {
                "animationType": "<?= $block->getAnimationJsName()?>",
                "duration": <?= $block->getDuration(); ?>,
                "easingFunction": "<?= $block->getEasingFunction(); ?>",
                "hoverElement": "<?= $block->getHoverElement();?>"
            }
        }
    }
</script>
