<?php
	$theme_dir = $this->helper('Oc\Theme\Helper\Data')->getConfig('general_oc/main_group/direction');
	$search_text = __('Search');
?>
<div class="noRount-main">
		<div class="page-title">
			<h1><?php echo __('HOW DID YOU GET HERE?'); ?></h1>
            <h2><?php echo __('This is really rare...'); ?></h2>
		</div>
		<div class="top-404">
			<p><?php echo __('The page you were looking for could not be found, perhaps you were looking for a page that no longer exists on the site, or you typed the wrong address.'); ?></p>
			<a href="<?php echo $block->getBaseUrl(); ?>"><?php echo __('Back to home page'); ?> ></a>
		</div>
	<div class="main-404">
			<div class="search-404">
					<form id="search_mini_form_404" class="search_mini_form_404" action="<?php echo $block->getBaseUrl(); ?>catalogsearch/result/" method="get">
						<div class="input-box searcbox">
								<input type="text" name="q" placeholder="<?= $search_text ?>" value="" class="input-text required-entry" maxlength="128" />
								<button type="submit" title="<?php echo __('Search') ?>" class="action primary search"><span><span><?php echo __('Search') ?></span></span></button>
						</div>
					</form>
			</div>
            <div class="data-404"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-right')->toHtml(); ?></div>
	</div>
</div>
