<?php
	$tab1title = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/tab1title');	
	$tab2title = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/tab2title');	
	$tab3title = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/tab3title');
	$theme_dir = $this->helper('Oc\Theme\Helper\Data')->getConfig('general_oc/main_group/direction');
	$search_text = $this->helper('Oc\Theme\Helper\Data')->getConfig('header_oc/header_main/search_text');
?>
<div class="noRount-main">
	<div class="container">
		<div class="page-title">
			<h1><?php echo __('404 Not Found'); ?></h1>
		</div>
		<div class="top-404">
			<p><?php echo __('The page you were looking for could not be found, perhaps you were looking for a page that no longer exists on the site, or you typed the wrong address.'); ?></p>
			<a href="<?php echo $block->getBaseUrl(); ?>"><?php echo __('Back to home page'); ?> ></a>
		</div>
	</div>
	<div class="main-404">
		<div class="container">
			<div class="search-404">
				<div class="block-search">
					<form id="search_mini_form_404" class="search_mini_form_404" action="<?php echo $block->getBaseUrl(); ?>catalogsearch/result/" method="get">
						<div class="input-box searcbox">
							<div class="control">
								<input type="text" name="q" placeholder="<?= $search_text ?>" value="" class="input-text required-entry" maxlength="128" />
							</div>
							<div class="actions">
								<button type="submit" title="<?php echo __('Search') ?>" class="action search"><span><span><?php echo __('Search') ?></span></span></button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>	
</div>