<?php
	$theme_dir = $this->helper('Oc\Theme\Helper\Data')->getConfig('general_oc/main_group/direction');	
	$title1 = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/title1');	
	$subtitle1 = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/subtitle1');		
	$link1 = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/link1');	
	$title2 = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/title2');	
	$subtitle2 = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/subtitle2');	
	$link2 = $this->helper('Oc\Theme\Helper\Data')->getConfig('oc_home/home/link2');
?>
<div class="home-content">
	<div class="content-left">
		<div class="main-banner">
			<?php echo $this->getLayout()->createBlock("\WeltPixel\OwlCarouselSlider\Block\Slider\Custom")->setSliderId('1')->toHtml(); ?>				
		</div>
		<div class="tree-top">
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-4 col-4 float-right"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('tree_top_1')->toHtml(); ?></div>
					<div class="col-md-4 col-sm-4 col-4 float-right"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('tree_top_2')->toHtml(); ?></div>
					<div class="col-md-4 col-sm-4 col-4 float-right"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('tree_top_3')->toHtml(); ?></div>
				</div>
			</div>
		</div>
		<div class="tree-top two-banners">
			<div class="container">
				<h2><?php echo $title1; ?></h2>
				<div class="block-title">
					<h3><?php echo $subtitle1; ?> <a href="<?php echo $link1; ?>"><?php echo __('To all items'); ?></a></h3>					
				</div>
				<div class="row">
					<div class="col-md-6 col-sm-6 col-6 float-right"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('two_middle_1')->toHtml(); ?></div>
					<div class="col-md-6 col-sm-6 col-6 float-right"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('two_middle_2')->toHtml(); ?></div>					
				</div>
				<div class="round-slider">
					<?php echo $this->getLayout()->createBlock("\WeltPixel\OwlCarouselSlider\Block\Slider\Custom")->setSliderId('2')->toHtml(); ?>
				</div>
			</div>
		</div>
		<div class="tree-top two-banners bottom">
			<div class="container">
				<h2><?php echo $title2; ?></h2>
				<div class="block-title">
					<h3><?php echo $subtitle2; ?> <a href="<?php echo $link2; ?>"><?php echo __('To all items'); ?></a></h3>					
				</div>
				<div class="row">
					<div class="col-md-6 col-sm-6 col-6 float-right"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_balloons')->toHtml(); ?></div>
					<div class="col-md-6 col-sm-6 col-6 float-right"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_accessories')->toHtml(); ?></div>					
				</div>
				<div class="round-slider">
					<?php echo $this->getLayout()->createBlock("\WeltPixel\OwlCarouselSlider\Block\Slider\Custom")->setSliderId('3')->toHtml(); ?>
				</div>
				<div class="home-brands">
					<div class="block"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-brands')->toHtml(); ?></div>
				</div>						
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	require(['jquery', 'owl_carousel', 'owl_config', 'domReady!'],function ($) {
        $('.owl-home').owlCarousel({
            nav:true,
            dots:false,
            autoplay : false,
            autoplayHoverPause : true,
            singleItem:true,
            pagination:false,
            navigation:true,
            lazyLoad : false,
            lazyLoad : false,
            <?php if($theme_dir!='ltr'): ?>
            rtl:true,
            <?php endif; ?>
            loop:true,
            margin : 20,
            responsive:{
                0:{
                    items:2
                },
                768:{
                    items:3
                },
                992:{
                    items:4
                },
                1300:{
                    items:6
                },
                1500:{
                    items:6
                }
            }
        });		
	});
</script>
