<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
    <?php  if($block->getCurrentCategory()->getImageUrl()): ?>
        <div class="image-desc">
    <?php endif; ?>
    <?php echo $this->getChildHtml('category.image.left'); ?>
    <?php if ($_description = $block->getCurrentCategory()->getDescription()) :?>
        <div class="category-description">
            <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
                $block->getCurrentCategory(),
                $_description,
                'description'
            ) ?>
        </div>
    <?php endif; ?>
    <?php  if($block->getCurrentCategory()->getImageUrl()): ?>
        </div>
<style>
    @media only screen and (min-width: 1200px) {
        .page-products .page-title-wrapper {
            position: absolute;
            z-index: 100;
            min-width: 700px;
        }
    }
</style>
<?php endif; ?>
