<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
$_category  = $block->getCurrentCategory();
$_imgHtml   = '';
?>
<?php if($_category->getImageUrl()): ?>
    <div class="category-image">
        <img src="<?php echo $_category->getImageUrl(); ?>" alt="<?php echo $block->escapeHtml($_category->getName()); ?>" title="<?php echo $block->escapeHtml($_category->getName()); ?>" class="image" />
    </div>
<?php endif; ?>
