<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<div class="nav-top">
    <img class="menu-close" src="<?php echo $block->getViewFileUrl('images/search-close.png'); ?>">
    <div class="nav-login" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <a href="<?php echo $block->getBaseUrl(); ?>customer/account/" data-bind="text: customer().fullname"></a>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <a href="<?php echo $block->getBaseUrl(); ?>customer/account/" data-bind="i18n:'Sign In'"></a>
        <!-- /ko -->
    </div>
</div>
<div class="nav-logo">
    <?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header\Logo")->setTemplate("Magento_Theme::html/header/logo.phtml")->toHtml(); ?>
</div>
<nav class="navigation navigation-custom" data-action="navigation">
    <ul class="main-nav" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>
<div class="menu-bottom">
    <?php //echo $this->getLayout()->createBlock("Magento\Store\Block\Switcher")->setTemplate("Magento_Store::switch/languages.phtml")->toHtml(); ?>
    <div class="mobile-nav-contact"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mobile-nav-contact')->toHtml(); ?></div>
</div>
<script type="text/x-magento-init">
{
	"*": {
		"Magento_Ui/js/core/app": {
			"components": {
				"customer": {
					"component": "Magento_Customer/js/view/customer"
				}
			}
		}
	}
}
</script>
