<?php
$_helper = $this->helper('Oc\Theme\Helper\Data');
?>
<div class="theme-header">
	<div class="header content">
				<div class="col-md-4 col-sm-4 col-4 header-right float-right">
                        <div class="cart-login">
                            <?php echo $this->getChildHtml('cat-mini'); ?>
                            <div class="float-right"><?php echo $this->getChildHtml('minicart'); ?></div>
                            <div class="header-fav float-right"><a href="<?php echo $block->getBaseUrl(); ?>wishlist/">&nbsp;</a></div>
                            <div class="header-login float-right">
                                <div class="login-block" data-bind="scope: 'customer'">
                                    <!-- ko if: customer().fullname  -->
                                        <a href="<?php echo $block->getBaseUrl(); ?>customer/account/" data-bind="text: customer().fullname"></a>
                                    <!-- /ko -->
                                    <!-- ko ifnot: customer().fullname  -->
                                    <a href="<?php echo $block->getBaseUrl(); ?>customer/account/" data-bind="i18n:'My Area'"></a>
                                    <!-- /ko -->
                                </div>
                            </div>
                            <div class="header-static float-right"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-shipping')->toHtml(); ?></div>
                        </div>
                    <div class="se-block">
                        <a href="javascript:void(0);" class="search-trig">&nbsp;</a>
                        <a href="javascript:void(0);" class="menu-trig">&nbsp;</a>
                        <?php echo $this->getChildHtml('topSearch'); ?>
                    </div>
				</div>
                <div class="col-md-4 col-sm-4 col-4 logo-block float-right">
                    <?php echo $this->getChildHtml('logo'); ?>
                </div>
				<div class="col-md-4 col-sm-4 col-4 float-right">
                    <div class="currency-block float-left">
                        <?php //echo $this->getChildHtml('store.settings.language'); ?>
                        <div class="panel wrapper">
                            <?php echo $this->getChildHtml('store.settings.currency'); ?>
                        </div>
                    </div>
				</div>
	</div>
</div>
<script type="text/javascript">
	require(['jquery'],function($){
	    var screenWidth = $( window ).width();
        $('.search-trig').click(function() {
            $(".se-block .block-search").animate({top: "0"});
        });
        $('.search-close').click(function() {
            $(".se-block .block-search").animate({top: "100%"});
        });
        $('.menu-trig').click(function() {
            $(".nav-sections").animate({left: "0"});
        });
        $('.menu-close').click(function() {
            $(".nav-sections").animate({left: "-100%"});
            $("ul.column-right").removeClass('active');
        });
        $(document).on("click", ".navigation li.back",function(event) {
            event.preventDefault();
            $("ul.column-right").removeClass('active');
        });
        $('.navigation .level0.parent').click(function() {
            $(this).find("ul.column-right").addClass('active');
        });
        if(screenWidth<=1199){
            $( ".navigation li.level0" ).each(function( index ) {
                $(this).find('a.level-top').attr('href','javascript:void(0);');
            });
        }
        if(screenWidth<=767){
            $(document).on("click", ".navigation ul.sub-menu table td p",function(event) {
                event.preventDefault();
                $(this).parent().toggleClass('active');
            });
        }
		$(document).scroll(function() {
			if($(window).scrollTop() === 0) {
				$('.page-header').removeClass('sticky-header');
			}
			else if($(window).scrollTop()>150){
				$('.page-header').addClass('sticky-header');
			}
		});
	});
</script>
<script type="text/x-magento-init">
{
	"*": {
		"Magento_Ui/js/core/app": {
			"components": {
				"customer": {
					"component": "Magento_Customer/js/view/customer"
				}
			}
		}
	}
}
</script>
