<?php $crumbs = $block->getCrumbs(); ?>
<?php if ($crumbs && is_array($crumbs)) : ?>
        <div class="breadcrumbs">
            <ul class="items">
                <?php
                foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <li class="item <?php echo $crumbName == 0 ? "home" : ""; ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?= /* @escapeNotVerified */
                            $crumbInfo['link'] ?>" title="<?= $block->escapeHtml(__($crumbInfo['title'])) ?>">
                                <?= $block->escapeHtml(__($crumbInfo['label'])) ?>
                            </a>
                        <?php else: ?>
                            <strong><?= $block->escapeHtml(__($crumbInfo['label'])) ?></strong>
                        <?php endif; ?>
                    </li>
                <?php
                endforeach; ?>
            </ul>
        </div>

<?php endif; ?>
